### ISSUE TITLE
error

### ISSUE THREAD

**Issue by elax46** [idealhack/synologynasbot#1]
`2020-12-04T13:18:32.366271+00:00 heroku[bot.1]: Starting process with command `python bot.py`
2020-12-04T13:18:32.966464+00:00 heroku[bot.1]: State changed from starting to up
2020-12-04T13:18:34.247520+00:00 heroku[bot.1]: Process exited with status 1
2020-12-04T13:18:34.447412+00:00 heroku[bot.1]: State changed from up to crashed
2020-12-04T13:18:34.196464+00:00 app[bot.1]: Traceback (most recent call last):
2020-12-04T13:18:34.196479+00:00 app[bot.1]:   File "bot.py", line 9, in <module>
2020-12-04T13:18:34.196485+00:00 app[bot.1]:     from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
2020-12-04T13:18:34.196485+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/telegram/__init__.py", line 21, in <module>
2020-12-04T13:18:34.196486+00:00 app[bot.1]:     from .base import TelegramObject
2020-12-04T13:18:34.196517+00:00 app[bot.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/telegram/base.py", line 42
2020-12-04T13:18:34.196518+00:00 app[bot.1]:     _id_attrs: Tuple[Any, ...] = ()
2020-12-04T13:18:34.196544+00:00 app[bot.1]:              ^
2020-12-04T13:18:34.196564+00:00 app[bot.1]: SyntaxError: invalid syntax`

**Comment by idealhack** [comment]
Apologies for the delayed reply, I don't have time to maintain this project since a while ago.

I would like to see you have the problem solved by yourself, or you have found better alternatives like https://github.com/magunetto/moviemagnetbot or an active fork of this project like https://github.com/brianchou452/synologynasbot.
